version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: joga_mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: joga_mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro

volumes:
  db_data:
